app:
  eureka-username: u
  eureka-password: p

server:
  port: ${PORT:0}

spring:
  application:
    name: transaction-api
  threads:
    virtual:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://${app.eureka-username}:${app.eureka-password}@localhost:8761/eureka/
    initial-instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
    
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
        - "*"