app:
  eureka-username: u
  eureka-password: p

server:
  port: 8443    

eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-username}:${app.eureka-password}@localhost:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
    
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: customer-api
        uri: lb://customer-api
        predicates:
        - Path=/customer/api/**
        filters: 
        - StripPrefix=2
      - id: transaction-api
        uri: lb://transaction-api
        predicates:
        - Path=/transaction/api/**
        filters: 
        - StripPrefix=2
        
management:
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
        - "*"
          