server:
  port: ${PORT:0}

spring:
  application:
    name: transaction-api
  threads:
    virtual:
      enabled: true
  datasource:
    password: demo
    url: jdbc:postgresql://127.0.0.1:5432/reto-01
    username: demo
    
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace
            
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    initial-instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
    
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
        - "*"